### PR TITLE
Add parser

### PR DESCRIPTION
**Pull request by dem4ron**

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
Thanks for the help! I don't fully understand this change.

edit: now I do understand

**Comment by ErikSchierboom** [comment]
Nevermind, I see that Josh also does this in https://github.com/exercism/codemirror-lang-wren. Thanks!

I'll tweak my build scripts later.

**Comment by ErikSchierboom** [comment]
Hmmm, I just double-checked what the difference is between this approach and my old approach and it's only indentation. Which means that I don't think this change fixes the problem :( Did you check locally whether the syntax highlighting worked?

**Comment by ErikSchierboom** [comment]
@dem4ron I'll figure it out and let you know what the solution is

**Comment by dem4ron** [comment]
> Did you check locally whether the syntax highlighting worked?

I didn't, because I couldn't make rollup to compile, and had very little time to play with it. But looking at different lang-packs that we did, we always did it like this. See Arturo or Gleam.

One major diff is that you were importing the grammar file and not a parser in index.ts.

Hope it works now, but let me know if it doesn't, then I'll set up a testing branch.

**Comment by ErikSchierboom** [comment]
I understand, but my point is that it doesn't matter what the `index.ts` file imports if it results in the same JS being output. But 🤷  I'll dig deeper

**Comment by ErikSchierboom** [comment]
@dem4ron It was a dependency issue: https://github.com/exercism/codemirror-lang-uiua/commit/5e305f81a3bf383337163e2e1001c17eff3bdc39 As I suspected, importing the syntax grammar was fine, there is no need to import the JS file as rollup will handle that.

**Pull request merged**
